### ISSUE TITLE
Performance on benchmark

### ISSUE THREAD

**Issue by adizhol** [gradslam/gradslam#17]
This is amazing work.
Have you tested it on KITTI or CityScapes datasets?

How does it compare to other SLAM pipelines?

**Comment by krrish94** [comment]
Hi @adizhol 

Thanks! Currently, gradslam only supports dense RGB-D SLAM pipelines - so we have only tested this on indoor reconstruction datasets.

In our [paper](https://arxiv.org/abs/1910.10672), we compare reconstruction (and egomotion) performance against their non-differentiable SLAM counterparts and find we perform on par.
