### ISSUE TITLE
How does gradslam generate the trajectory file (e.g. for tum-dataset)?

### ISSUE THREAD

**Issue by linpeisensh** [gradslam/gradslam#23]
Thank you for your excellent work!

Could you please tell me, How gradslam generate the trajectory file (e.g. for tum-dataset)?  Or do I need to write this function myself?

**Comment by krrish94** [comment]
@linpeisensh when you run the following line (see tutorial https://gradslam.readthedocs.io/en/latest/tutorials/pointfusion_tutorial.html#Basic-PointFusion), the `recovered_poses` variable is the trajectory

```
pointclouds, recovered_poses = slam(rgbdimages)
```

If you'd like to visualize the entire trajectory, we don't have an off-the-shelf function to do that (but it is a great feature request). You might want to see https://gradslam.readthedocs.io/en/latest/tutorials/pointfusion_tutorial.html#Step-by-step-PointFusion
