### ISSUE TITLE
KinectFusion support

### ISSUE THREAD

**Issue by SilvioGiancola** [gradslam/gradslam#24]
Hi,

I would like to reproduce the performances of KinectFusion from your paper. Do you have reproducible code for it? If not, are you planning to release it?

Best,

**Comment by krrish94** [comment]
@SilvioGiancola KinectFusion is indeed on our roadmap for version 0.2.0

**Comment by SilvioGiancola** [comment]
Great, thank you for your prompt answer. Is there a candidate date for the release of version 0.2.0?

**Comment by krrish94** [comment]
We're actively working on it -- although we want to get a sense of a stable API and feature requests first

My estimate would be first or second week of Jan

We will make our roadmap public later this week, and hopefully a lot of people will be eager to contrib :)

**Comment by SilvioGiancola** [comment]
Thank you for your great work, looking forward to build upon it and contrib :)

**Comment by cxt98** [comment]
Hi, is there any progress update on releasing KinectFusion?

**Comment by krrish94** [comment]
Closing this, as we have been working on `PointFusion` as the sole candidate in learning applications (in part due to the prohibitive memory requirements imposed by `KinectFusion` on large scenes -- in the absense of sparse voxel-based hashing methods)
