### ISSUE TITLE
PyTorch Auto Differentiation

### ISSUE THREAD

**Issue by JeffreyYH** [gradslam/gradslam#26]
## Where is the implementation of PyTorch auto differentiation ? 

Hi, thanks for sharing the code. I checked the code of gauss_newton_solve in icputils.py but didn't found you using auto differentiation to implement LM solver.

Thank you!

**Comment by krrish94** [comment]
@JeffreyYH I'm confused about the issue.

Do you mean that we don't have an explicitly implemented `backward` pass for ICP? That is intended, as we build each of our modules with PyTorch ops that are inturn differentiable (and thus we don't need an explicit backward method).

**Comment by JeffreyYH** [comment]
Thank you!
