### ISSUE TITLE
Colored ICP

### ISSUE THREAD

**Issue by erezposner** [gradslam/gradslam#27]
Hi,
Is there a plan to incorporate color ICP just like OPEN3D implemented based on J.Park, Q.-Y. Zhou, and V. Koltun, Colored Point Cloud Registration Revisited, ICCV, 2017

Thanks

**Comment by saryazdi** [comment]
Hi @erezposner ,

This is not on the roadmap at the moment, but if anyone wants to take initiative we can merge their code.
