### ISSUE TITLE
To save the pointcloud once generated.

### ISSUE THREAD

**Issue by Gowtham171996** [gradslam/gradslam#45]
Once the point cloud is generated, it would be best if we can save it, or better create a mesh and save it.

**Comment by krrish94** [comment]
The pointclouds can be converted to open3d geometries (as shown in the examples) by calling `.open3d(idx)` on the `pointclouds` object returned by `PointFusion`. They can then be exported using the [`open3d.io.write_pointcloud`](http://www.open3d.org/docs/release/python_api/open3d.io.write_point_cloud.html) method
