### ISSUE TITLE
Is the Poses Data Actually Used in the SLAM Process?

### ISSUE THREAD

**Issue by stanleyshly** [gradslam/gradslam#46]
Looking at this example: [https://github.com/gradslam/gradslam/blob/main/examples/tutorials/pointfusion_tutorial.ipynb](url), it seems like the poses data is only actually used in the "Advanced visualization" section, and is actually not even used in the SLAM process for the odometry step, given that slam.step seems to return the a pointcloud **and** a poses array. Given that is the case, if I write my own custom dataloader, and only load in Depth and Color Images, and place all of the reconstruct pose data into an array, and run the plotly_map_update_visualization(advanced visualization function) with that, would it work alright?

**Comment by eleftherita** [comment]
Hello there...i am currently facing the same issue about camera poses...did you manage to run the code with only RGBD inputs? 
Thank you in advance.

**Comment by zyc-bit** [comment]
> Hello there...i am currently facing the same issue about camera poses...did you manage to run the code with only RGBD inputs? Thank you in advance.

same issue
