### ISSUE TITLE
how the jacobian is derived?

### ISSUE THREAD

**Issue by lqiang2003cn** [gradslam/gradslam#53]
hi, i wonder how the jacobian is derived:
 [nx, ny, nz, nz * sy - ny * sz, nx * sz - nz * sx, ny * sx - nx * sy]  ?
in other words, what is the exact form of your residual function r ? thanks.

**Comment by krrish94** [comment]
Hi @lqiang2003cn, the residual function this Jacobian corresponds to is the point-to-plane ICP metric. For a tech report discussing and deriving this, one pointer is https://www.cs.princeton.edu/~smr/papers/icpstability.pdf
